update=07/03/2017 16:44:12
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName31=C:/Program Files/KiCad/share/kicad/library/74xx
LibName32=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName33=C:/Program Files/KiCad/share/kicad/library/actel
LibName34=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName35=C:/Program Files/KiCad/share/kicad/library/allegro
LibName36=C:/Program Files/KiCad/share/kicad/library/Altera
LibName37=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName38=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName39=C:/Program Files/KiCad/share/kicad/library/atmel
LibName40=C:/Program Files/KiCad/share/kicad/library/audio
LibName41=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName42=C:/Program Files/KiCad/share/kicad/library/bbd
LibName43=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName44=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName45=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName46=C:/Program Files/KiCad/share/kicad/library/conn
LibName47=C:/Program Files/KiCad/share/kicad/library/contrib
LibName48=C:/Program Files/KiCad/share/kicad/library/cypress
LibName49=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName50=C:/Program Files/KiCad/share/kicad/library/device
LibName51=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName52=C:/Program Files/KiCad/share/kicad/library/diode
LibName53=C:/Program Files/KiCad/share/kicad/library/display
LibName54=C:/Program Files/KiCad/share/kicad/library/dsp
LibName55=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName56=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName57=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName58=C:/Program Files/KiCad/share/kicad/library/gennum
LibName59=C:/Program Files/KiCad/share/kicad/library/graphic
LibName60=C:/Program Files/KiCad/share/kicad/library/hc11
LibName61=C:/Program Files/KiCad/share/kicad/library/intel
LibName62=C:/Program Files/KiCad/share/kicad/library/interface
LibName63=C:/Program Files/KiCad/share/kicad/library/ir
LibName64=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName65=C:/Program Files/KiCad/share/kicad/library/linear
LibName66=C:/Program Files/KiCad/share/kicad/library/logo
LibName67=C:/Program Files/KiCad/share/kicad/library/maxim
LibName68=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName69=C:/Program Files/KiCad/share/kicad/library/memory
LibName70=C:/Program Files/KiCad/share/kicad/library/microchip
LibName71=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName72=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName73=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName74=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName75=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName76=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName77=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName78=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName79=C:/Program Files/KiCad/share/kicad/library/motorola
LibName80=C:/Program Files/KiCad/share/kicad/library/motors
LibName81=C:/Program Files/KiCad/share/kicad/library/msp430
LibName82=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName83=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName84=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName85=C:/Program Files/KiCad/share/kicad/library/opto
LibName86=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName87=C:/Program Files/KiCad/share/kicad/library/philips
LibName88=C:/Program Files/KiCad/share/kicad/library/power
LibName89=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName90=C:/Program Files/KiCad/share/kicad/library/powerint
LibName91=C:/Program Files/KiCad/share/kicad/library/pspice
LibName92=C:/Program Files/KiCad/share/kicad/library/references
LibName93=C:/Program Files/KiCad/share/kicad/library/regul
LibName94=C:/Program Files/KiCad/share/kicad/library/relays
LibName95=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName96=C:/Program Files/KiCad/share/kicad/library/sensors
LibName97=C:/Program Files/KiCad/share/kicad/library/silabs
LibName98=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName99=C:/Program Files/KiCad/share/kicad/library/stm8
LibName100=C:/Program Files/KiCad/share/kicad/library/stm32
LibName101=C:/Program Files/KiCad/share/kicad/library/supertex
LibName102=C:/Program Files/KiCad/share/kicad/library/switches
LibName103=C:/Program Files/KiCad/share/kicad/library/texas
LibName104=C:/Program Files/KiCad/share/kicad/library/transf
LibName105=C:/Program Files/KiCad/share/kicad/library/transistors
LibName106=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName107=C:/Program Files/KiCad/share/kicad/library/valves
LibName108=C:/Program Files/KiCad/share/kicad/library/video
LibName109=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName110=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName111=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName112=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName113=C:/Program Files/KiCad/share/kicad/library/zetex
LibName114=C:/Program Files/KiCad/share/kicad/library/Zilog
[cvpcb]
version=1
NetIExt=net
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
